name: test de git actions

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola!"
      - name: fecha
        run: date
      - run: ls -l